// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA77b0hKtJMphexqxCd9N8wXSpvqVmDcU',
    appId: '1:931789410075:web:3cc37eaa6d8455cf118dbe',
    messagingSenderId: '931789410075',
    projectId: 'flutterbosschat',
    authDomain: 'flutterbosschat.firebaseapp.com',
    storageBucket: 'flutterbosschat.appspot.com',
    measurementId: 'G-0BBXZ1DTWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL1ckcOyJKymRswGcvfrDcTRVguUn1vBc',
    appId: '1:931789410075:android:24c4ef171b901a65118dbe',
    messagingSenderId: '931789410075',
    projectId: 'flutterbosschat',
    storageBucket: 'flutterbosschat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybpUrmqSQBnBUZcA4J3E-8ENliK7ry5M',
    appId: '1:931789410075:ios:16158a7bd193f116118dbe',
    messagingSenderId: '931789410075',
    projectId: 'flutterbosschat',
    storageBucket: 'flutterbosschat.appspot.com',
    iosClientId: '931789410075-i1g0pfob5du26qpo12p9t6ouv0ena4s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bossChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDybpUrmqSQBnBUZcA4J3E-8ENliK7ry5M',
    appId: '1:931789410075:ios:16158a7bd193f116118dbe',
    messagingSenderId: '931789410075',
    projectId: 'flutterbosschat',
    storageBucket: 'flutterbosschat.appspot.com',
    iosClientId: '931789410075-i1g0pfob5du26qpo12p9t6ouv0ena4s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bossChat',
  );
}
